<a href="https://colab.research.google.com/github/azrapatvi/Ml_practice/blob/main/9_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
from sklearn.datasets import make_classification

X,y=make_classification(
    n_samples=1000,
    n_features=3,
    n_classes=2,
    n_redundant=1,
  random_state=42
)

In [37]:
X

array([[ 2.48547786,  2.39963589, -1.46526917],
       [ 2.20403962, -1.06965652,  0.00979545],
       [-0.5726534 , -0.75494788,  0.42032991],
       ...,
       [-0.41608875,  0.46668963, -0.11024494],
       [-1.57936997,  2.48498245, -0.71060102],
       [-0.43277356,  0.89093028, -0.28069604]])

In [38]:
pd.DataFrame(X)

,0,1,2
0,2.485478,2.399636,-1.465269
1,2.204040,-1.069657,0.009795
2,-0.572653,-0.754948,0.420330
3,-0.990616,3.909762,-1.408300
4,-1.287894,1.896194,-0.526160
...,...,...,...
995,-1.301522,-2.361662,1.219735
996,1.130708,-0.755899,0.089836
997,-0.416089,0.466690,-0.110245
998,-1.579370,2.484982,-0.710601


In [39]:
y

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,

In [40]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [41]:
X_train

array([[ 1.67694767, -1.83276749,  0.42461701],
       [ 1.32562619,  1.33361742, -0.80351577],
       [-1.04613896,  0.09842593,  0.16291864],
       ...,
       [-1.20237056, -0.96824467,  0.62998239],
       [ 0.24438526, -0.92969585,  0.33316248],
       [ 0.25545092,  0.83840655, -0.3928818 ]])

In [42]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(

)

In [43]:
model.fit(X_train,y_train)

KNeighborsClassifier()

In [44]:
y_pred=model.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.895
[[87  9]
 [12 92]]
              precision    recall  f1-score   support

           0       0.88      0.91      0.89        96
           1       0.91      0.88      0.90       104

    accuracy                           0.90       200
   macro avg       0.89      0.90      0.89       200
weighted avg       0.90      0.90      0.90       200



In [46]:
params = {
    'n_neighbors': [3, 5, 7, 9],
    'algorithm': ['brute', 'kd_tree', 'ball_tree']
}

In [47]:
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(
    estimator=model,
    param_grid=params,
    scoring='accuracy',
    cv=5

)

In [48]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['brute', 'kd_tree', 'ball_tree'],
                         'n_neighbors': [3, 5, 7, 9]},
             scoring='accuracy')

In [49]:
grid.best_params_

{'algorithm': 'brute', 'n_neighbors': 9}

In [50]:
y_pred=grid.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.895
[[88  8]
 [13 91]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89        96
           1       0.92      0.88      0.90       104

    accuracy                           0.90       200
   macro avg       0.90      0.90      0.89       200
weighted avg       0.90      0.90      0.90       200

