<a href="https://colab.research.google.com/github/azrapatvi/Ml_practice/blob/main/Logistic_Regression_Multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Logistic regression for multiclass classification

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000,
    n_classes=3,
    n_features=4,
    n_informative=3,
    n_redundant=0,
    random_state=42
)

In [ ]:
X

array([[ 1.25923324,  0.49750289,  1.49622778, -1.53837425],
       [ 1.52803136, -1.90678554,  0.76794206, -0.60639162],
       [ 0.47263035, -1.58227847,  0.28118552, -0.22830519],
       ...,
       [ 0.60824619, -1.21022818, -0.63967765,  1.56967876],
       [ 0.76883968, -0.50678268,  1.95549875,  0.23725984],
       [ 0.73463755,  0.71646777,  0.97915597,  0.58783253]])

In [ ]:
pd.DataFrame(X)

,0,1,2,3
0,1.259233,0.497503,1.496228,-1.538374
1,1.528031,-1.906786,0.767942,-0.606392
2,0.472630,-1.582278,0.281186,-0.228305
3,0.995582,-0.777573,0.131273,1.713800
4,0.418206,-1.315077,-0.823726,-0.771573
...,...,...,...,...
995,-0.104343,-0.064477,1.599369,-0.777523
996,1.303508,-0.521920,-0.241908,-1.668966
997,0.608246,-1.210228,-0.639678,1.569679
998,0.768840,-0.506783,1.955499,0.237260


In [ ]:
y

array([0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 1, 1,
       2, 2, 1, 1, 0, 2, 1, 2, 2, 0, 1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 2, 2,
       1, 0, 1, 0, 2, 1, 1, 2, 0, 2, 0, 2, 2, 0, 1, 2, 2, 0, 0, 2, 0, 0,
       2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 0, 2, 1, 0,
       2, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2, 2, 0, 1, 1, 0, 1, 1, 0, 2, 2, 2,
       0, 0, 2, 1, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0,
       0, 1, 0, 0, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 2, 1,
       1, 0, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 1,
       0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 2, 1, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0,
       1, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2,
       0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 2, 2, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0,
       0, 2, 1, 1, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 2, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 0, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
# ovr- one vs rest
# suppose you want ot classify the data into categories such as cat dog and bird
# so ovr will do like below

    #          Logistic Regression
    #                 │
    #     ┌───────────┼───────────┐
    #     ↓           ↓           ↓
    #  Cat vs Rest  Dog vs Rest  Bird vs Rest

# Suppose a new animal comes in.

# The models might say:

# Cat model  → 0.20
# Dog model  → 0.85
# Bird model → 0.30

# Highest score is:# Dog = 0.85

# So the final prediction is:# Dog

# That's One-vs-Rest.

from sklearn.linear_model import LogisticRegression

model=LogisticRegression(multi_class='ovr')

model

LogisticRegression(multi_class='ovr')

In [ ]:
model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [ ]:
y_pred=model.predict(X_test)

y_pred

array([2, 2, 2, 1, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 2, 2, 0, 2, 2, 0, 0,
       0, 1, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 2, 2, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1, 0, 0, 2, 2, 0,
       0, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 1, 2,
       0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 1, 2, 2, 1, 1,
       0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 0, 0, 2,
       2, 2, 2, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 0,
       2, 1, 0, 0, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2,
       2, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0])

In [ ]:
y_test

array([2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2,
       2, 0, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0,
       1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 1, 1, 0,
       1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1, 2, 1,
       1, 2, 2, 0, 1, 1, 0, 0, 1, 2, 1, 0, 2, 0, 2, 0, 0, 0, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 2,
       2, 2, 1, 0, 2, 2, 1, 1, 2, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 2, 1, 0,
       0, 0, 1, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 2, 2, 1, 2,
       1, 1, 0, 1, 0, 2, 0, 2, 1, 0, 1, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2,
       1, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 2, 1, 1, 1, 2, 0, 0, 0,
       2, 0, 1, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 0, 0, 0, 2, 1, 2, 0, 0,
       1, 2, 0, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 0, 0, 2, 1,
       2, 1, 2, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 1, 1, 2, 0,
       0, 1, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6466666666666666
[[82 17  6]
 [47 27 17]
 [ 6 13 85]]
              precision    recall  f1-score   support

           0       0.61      0.78      0.68       105
           1       0.47      0.30      0.36        91
           2       0.79      0.82      0.80       104

    accuracy                           0.65       300
   macro avg       0.62      0.63      0.62       300
weighted avg       0.63      0.65      0.63       300



In [ ]:

model=LogisticRegression(multi_class='multinomial')

model

LogisticRegression(multi_class='multinomial')

In [ ]:
model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='multinomial')

In [ ]:
y_pred=model.predict(X_test)

y_pred

array([2, 2, 2, 1, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2,
       2, 1, 1, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 2, 2, 0, 2, 2, 2, 0,
       2, 1, 2, 0, 2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 2, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 2, 0, 2, 0, 1, 0, 0, 2, 2, 0,
       0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2, 1, 2,
       0, 1, 0, 2, 2, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 1, 2, 1, 2, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1, 1,
       0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 0, 1, 2, 1, 1, 0, 0, 2,
       2, 2, 2, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 0,
       2, 1, 0, 0, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0,
       1, 2, 0, 0, 0, 2, 0, 1, 2, 1, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 2, 2,
       2, 1, 2, 0, 1, 1, 0, 2, 0, 2, 0, 1, 0, 1, 0, 2, 0, 1, 2, 0, 2, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.65
[[76 24  5]
 [36 40 15]
 [ 6 19 79]]
              precision    recall  f1-score   support

           0       0.64      0.72      0.68       105
           1       0.48      0.44      0.46        91
           2       0.80      0.76      0.78       104

    accuracy                           0.65       300
   macro avg       0.64      0.64      0.64       300
weighted avg       0.65      0.65      0.65       300



In [ ]:

model=LogisticRegression()

model

LogisticRegression()

In [ ]:
# hyperparameter tuning

from sklearn.model_selection import GridSearchCV

params={
    'penalty':['l1','l2','elasticnet'],
    'C':[0.001,0.01,0.1,1,10],
    'multi_class':['ovr','multinomial'],
    "solver":['lbfgs','saga','liblinear','newton-cg']
}

grid=GridSearchCV(estimator=model,param_grid=params,cv=5,scoring="accuracy",n_jobs=-1)

In [ ]:
grid

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10],
                         'multi_class': ['ovr', 'multinomial'],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'saga', 'liblinear', 'newton-cg']},
             scoring='accuracy')

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
350 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solv

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10],
                         'multi_class': ['ovr', 'multinomial'],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'saga', 'liblinear', 'newton-cg']},
             scoring='accuracy')

In [ ]:
grid.best_params_

{'C': 0.01, 'multi_class': 'ovr', 'penalty': 'l2', 'solver': 'liblinear'}

In [ ]:
grid.best_score_

np.float64(0.6542857142857142)

In [ ]:

y_pred=grid.predict(X_test)


In [ ]:
y_pred

array([2, 2, 2, 1, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0,
       0, 2, 2, 2, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0,
       0, 1, 2, 1, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 1, 2,
       0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 1, 2, 0, 2, 0, 2, 2, 1, 0, 0, 0, 2, 2, 0, 2, 1, 2, 2, 1, 2,
       0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 0, 0, 2,
       2, 2, 2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 2, 2, 2, 0, 0, 1, 0, 0, 2, 0,
       2, 2, 0, 0, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 2, 1, 1, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2,
       2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.67
[[85  8 12]
 [50 21 20]
 [ 6  3 95]]
              precision    recall  f1-score   support

           0       0.60      0.81      0.69       105
           1       0.66      0.23      0.34        91
           2       0.75      0.91      0.82       104

    accuracy                           0.67       300
   macro avg       0.67      0.65      0.62       300
weighted avg       0.67      0.67      0.63       300

